name: Deploy Documentation to GitHub Pages

on:
  push:
    branches:
      - main  # or master, depending on your default branch name
    paths:
      - 'docs/**'  # Only trigger when docs are updated
      - '_config.yml'
      - '_layouts/**'
      - '_includes/**'
      - 'assets/**'
      - '.github/workflows/deploy-docs.yml'
  # Allow manual trigger
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.183.0
        with:
          ruby-version: '3.1'
          bundler-cache: true
          
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Install Dependencies
        run: |
          gem install bundler
          bundle install
          npm install glob
          
      - name: Prepare Docs
        run: |
          chmod +x scripts/prepare-docs-for-jekyll.js
          node scripts/prepare-docs-for-jekyll.js
          
      - name: Build Site
        run: bundle exec jekyll build
        
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: "_site/"

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4